BEGIN;
CREATE TABLE "entrez2ensembl" ("tax_id" INTEGER, "entrez_id" INTEGER, "ensembl_id" VARCHAR);
CREATE INDEX v6_tax_id ON entrez2ensembl (tax_id);
CREATE INDEX v7_entrez_id ON entrez2ensembl (entrez_id);
CREATE INDEX v8_ensembl_id ON entrez2ensembl (ensembl_id);
CREATE TABLE "gene_history" ("tax_id" INTEGER,"entrez_id" INTEGER DEFAULT (null) ,"discontinued_id" INTEGER,"discontinued_symbol" VARCHAR,"discontinued_date" VARCHAR);
CREATE TABLE "human_gene" ("ensembl_id" VARCHAR, "entrez_id" INTEGER, "description" TEXT, "chromosome_name" VARCHAR, "start_position" INTEGER, "end_position" INTEGER);
CREATE INDEX v9_entrez_id ON human_gene (entrez_id);
CREATE INDEX v10_ensembl_id ON human_gene (ensembl_id);
CREATE INDEX v11_chromosome_name ON human_gene (chromosome_name);
CREATE INDEX v12_start_position ON human_gene (start_position);
CREATE INDEX v12_end_position ON human_gene (end_position);
CREATE TABLE "human_homolog" ("human" VARCHAR,"homolog" VARCHAR DEFAULT (null) ,"homolog_type" VARCHAR DEFAULT (null) ,"dn" FLOAT,"ds" FLOAT,"species" VARCHAR);
CREATE INDEX v13_human ON human_homolog (human);
CREATE INDEX v14_homolog ON human_homolog (homolog);
CREATE INDEX v15_homolog_type ON human_homolog (homolog_type);
CREATE INDEX v16_species ON human_homolog (species);
CREATE TABLE "human_variation" ("variation_id" VARCHAR, "variation_source" VARCHAR, "chromosome_name" VARCHAR, "position" INTEGER, "allele" VARCHAR);
CREATE INDEX v17_variation_id ON human_variation (variation_id);
CREATE INDEX v18_variation_source ON human_variation (variation_source);
CREATE INDEX v19_chromosome_name ON human_variation (chromosome_name);
CREATE INDEX v20_position ON human_variation (position);
CREATE TABLE "human_variation2gene" ("variation_id" VARCHAR,"entrez_id" VARCHAR DEFAULT (null) ,"position" VARCHAR,"distance" INTEGER);
CREATE INDEX v21_variation_id ON human_variation2gene (variation_id);
CREATE INDEX v22_entrez_id ON human_variation2gene (entrez_id);
CREATE INDEX v23_position ON human_variation2gene (position);
CREATE INDEX v24_distance ON human_variation2gene (distance);
CREATE TABLE "source_OMIM" ("locus_mim_acc" INTEGER NOT NULL , "entrez_id" INTEGER NOT NULL , "disorder_mim_acc" INTEGER, "disorders" TEXT NOT NULL , "gene_symbols" TEXT, "location" VARCHAR);
CREATE INDEX v1_locus_mim_acc ON source_OMIM (locus_mim_acc);
CREATE INDEX v2_entrez_id ON source_OMIM (entrez_id);
CREATE INDEX v2_disorder_mim_acc ON source_OMIM (disorder_mim_acc);
CREATE INDEX v2_location ON source_OMIM (location);
CREATE TABLE "mapping_OMIM_raw" ("text" TEXT, "term_id" VARCHAR, "term_name" VARCHAR, "mapping_score" INTEGER, "mapping_tool" VARCHAR);
CREATE INDEX mor_term_id ON mapping_OMIM_raw (term_id);
CREATE INDEX mor_mapping_score ON mapping_OMIM_raw (mapping_score);
CREATE INDEX mor_mapping_tool ON mapping_OMIM_raw (mapping_tool);
CREATE TABLE "mapping_OMIM_filter" ( "text" TEXT, "term_id" VARCHAR, "term_name" VARCHAR, "mapping_score" INTEGER, "mapping_tool" VARCHAR);
CREATE INDEX mof_term_id ON mapping_OMIM_filter (term_id);
CREATE INDEX mof_mapping_score ON mapping_OMIM_filter (mapping_score);
CREATE INDEX mof_mapping_tool ON mapping_OMIM_filter (mapping_tool);
CREATE TABLE "mapping_VAR_raw" ("text" TEXT, "term_id" VARCHAR, "term_name" VARCHAR, "mapping_score" INTEGER, "mapping_tool" VARCHAR);
CREATE INDEX mvr_term_id ON mapping_VAR_raw (term_id);
CREATE INDEX mvr_mapping_score ON mapping_VAR_raw (mapping_score);
CREATE INDEX mvr_mapping_tool ON mapping_VAR_raw (mapping_tool);
CREATE TABLE "mapping_VAR_filter" ("text" TEXT, "term_id" VARCHAR, "term_name" VARCHAR, "mapping_score" INTEGER, "mapping_tool" VARCHAR);
CREATE INDEX mvf_term_id ON mapping_VAR_filter (term_id);
CREATE INDEX mvf_mapping_score ON mapping_VAR_filter (mapping_score);
CREATE INDEX mvf_mapping_tool ON mapping_VAR_filter (mapping_tool);
CREATE TABLE "mapping_GENERIF_raw" ( "text" TEXT, "term_id" VARCHAR, "term_name" VARCHAR, "mapping_score" INTEGER, "mapping_tool" VARCHAR);
CREATE INDEX mgr_term_id ON mapping_GENERIF_raw (term_id);
CREATE INDEX mgr_mapping_score ON mapping_GENERIF_raw (mapping_score);
CREATE INDEX mgr_mapping_tool ON mapping_GENERIF_raw (mapping_tool);
CREATE TABLE "mapping_GENERIF_filter" ( "text" TEXT, "term_id" VARCHAR, "term_name" VARCHAR, "mapping_score" INTEGER, "mapping_tool" VARCHAR);
CREATE INDEX mgf_term_id ON mapping_GENERIF_filter (term_id);
CREATE INDEX mgf_mapping_score ON mapping_GENERIF_filter (mapping_score);
CREATE INDEX mgf_mapping_tool ON mapping_GENERIF_filter (mapping_tool);
CREATE TABLE "mapping_HUGE_raw" ( "text" TEXT, "term_id" VARCHAR, "term_name" VARCHAR, "mapping_score" INTEGER, "mapping_tool" VARCHAR);
CREATE INDEX mapping_HUGE_raw_term_id ON mapping_HUGE_raw (term_id);
CREATE INDEX mapping_HUGE_raw_mapping_score ON mapping_HUGE_raw (mapping_score);
CREATE INDEX mapping_HUGE_raw_mapping_tool ON mapping_HUGE_raw (mapping_tool);
CREATE TABLE "mapping_HUGE_filter" ( "text" TEXT, "term_id" VARCHAR, "term_name" VARCHAR, "mapping_score" INTEGER, "mapping_tool" VARCHAR);
CREATE INDEX mapping_HUGE_filter_term_id ON mapping_HUGE_filter (term_id);
CREATE INDEX mapping_HUGE_filter_mapping_score ON mapping_HUGE_filter (mapping_score);
CREATE INDEX mapping_HUGE_filter_mapping_tool ON mapping_HUGE_filter (mapping_tool);
CREATE TABLE "source_HUGE" ("entrez_id" INTEGER DEFAULT (null) ,"text" TEXT);
CREATE TABLE "source_meta" ("name" VARCHAR,"full_name" VARCHAR,"description" TEXT,"ref" VARCHAR,"table_source" VARCHAR DEFAULT (null) ,"table_mapping" VARCHAR,"table_d2g" VARCHAR);
CREATE TABLE "source_VAR" ("entrez_id" INT DEFAULT (null) ,"relative_position" VARCHAR,"distance" VARCHAR,"variation_id" VARCHAR,"variation_source" VARCHAR,"chromosome_name" VARCHAR,"position" INTEGER,"allele" VARCHAR,"study_type" VARCHAR,"study_external_ref" VARCHAR,"study_description" VARCHAR,"study_source" VARCHAR,"phenotype_description" TEXT,"associated_variant_risk_allele" VARCHAR,"p_value" FLOAT);
CREATE TABLE "source_DISGENET" ("entrez_id" INTEGER,"geneSymbol" VARCHAR,"geneName" VARCHAR, "diseaseId" VARCHAR,"diseaseName" VARCHAR,"score" DOUBLE, "NumberOfPubmeds" INTEGER,"associationType" VARCHAR,"source" VARCHAR);
CREATE INDEX source_DISGENET_entrez_id ON source_DISGENET (entrez_id);
CREATE INDEX source_DISGENET_geneSymbol ON source_DISGENET (geneSymbol);
CREATE INDEX source_DISGENET_geneName ON source_DISGENET (geneName);
CREATE INDEX source_DISGENET_diseaseId ON source_DISGENET (diseaseId);
CREATE INDEX source_DISGENET_diseaseName ON source_DISGENET (diseaseName);
CREATE INDEX source_DISGENET_score ON source_DISGENET (score);
CREATE INDEX source_DISGENET_NumberOfPubmeds ON source_DISGENET (NumberOfPubmeds);
CREATE INDEX source_DISGENET_associationType ON source_DISGENET (associationType);
CREATE INDEX source_DISGENET_source ON source_DISGENET (source);
CREATE TABLE "mapping_DISGENET_raw" ( "text" TEXT, "term_id" VARCHAR, "term_name" VARCHAR, "mapping_score" INTEGER, "mapping_tool" VARCHAR);
CREATE INDEX mapping_DISGENET_raw_term_id ON mapping_DISGENET_raw (term_id);
CREATE INDEX mapping_DISGENET_raw_mapping_score ON mapping_DISGENET_raw (mapping_score);
CREATE INDEX mapping_DISGENET_raw_mapping_tool ON mapping_DISGENET_raw (mapping_tool);
CREATE TABLE "mapping_DISGENET_filter" ( "text" TEXT, "term_id" VARCHAR, "term_name" VARCHAR, "mapping_score" INTEGER, "mapping_tool" VARCHAR);
CREATE INDEX mapping_DISGENET_filter_term_id ON mapping_DISGENET_filter (term_id);
CREATE INDEX mapping_DISGENET_filter_mapping_score ON mapping_DISGENET_filter (mapping_score);
CREATE INDEX mapping_DISGENET_filter_mapping_tool ON mapping_DISGENET_filter (mapping_tool);
CREATE TABLE "human_d2g" ("entrez_id" INTEGER, "term_id" VARCHAR, "source" VARCHAR, "source_count" INT);
CREATE INDEX human_g2d_term_id ON "human_d2g" (term_id);
CREATE INDEX human_g2d_entrez_id ON "human_d2g" (entrez_id);
CREATE INDEX human_g2d_source ON "human_d2g" (source);
CREATE INDEX human_g2d_source_count ON "human_d2g" (source_count);
CREATE TABLE "d2g_OMIM"("locus_mim_acc" INT,"entrez_id" INT,"disorder_mim_acc" INT,"disorders" TEXT,"gene_symbols" VARCHAR,"location" VARCHAR,"term_id" VARCHAR,"term_name" VARCHAR,"mapping_tool" VARCHAR,"mapping_confident" INT);
CREATE INDEX v2_d2g_OMIM ON d2g_OMIM (locus_mim_acc);
CREATE INDEX v3_d2g_OMIM ON d2g_OMIM (entrez_id);
CREATE INDEX v4_d2g_OMIM ON d2g_OMIM (disorder_mim_acc);
CREATE INDEX v5_d2g_OMIM ON d2g_OMIM (location);
CREATE INDEX v6_d2g_OMIM ON d2g_OMIM (term_id);
CREATE INDEX v7_d2g_OMIM ON d2g_OMIM (term_name);
CREATE INDEX v8_d2g_OMIM ON d2g_OMIM (mapping_tool);
CREATE INDEX v9_d2g_OMIM ON d2g_OMIM (mapping_confident);
CREATE TABLE "d2g_DISGENET"("entrez_id" INT,"geneSymbol" VARCHAR,"geneName" VARCHAR,"diseaseId" VARCHAR,"diseaseName" VARCHAR,"score" REAL,"NumberOfPubmeds" INT,"associationType" VARCHAR,"source" VARCHAR,"term_id" VARCHAR,"term_name" VARCHAR,"mapping_tool" VARCHAR,"mapping_confident" INT);
CREATE INDEX v2_d2g_DISGENET ON d2g_DISGENET (term_id);
CREATE INDEX v3_d2g_DISGENET ON d2g_DISGENET (term_name);
CREATE INDEX v4_d2g_DISGENET ON d2g_DISGENET (entrez_id);
CREATE TABLE "d2g_HUGE"("entrez_id" INT,"text" TEXT,"term_id" VARCHAR,"term_name" VARCHAR,"mapping_tool" VARCHAR,"mapping_confident" INT);
CREATE INDEX v2_d2g_HUGE ON d2g_HUGE (term_id);
CREATE INDEX v3_d2g_HUGE ON d2g_HUGE (term_name);
CREATE INDEX v4_d2g_HUGE ON d2g_HUGE (entrez_id);
CREATE INDEX v5_d2g_HUGE ON d2g_HUGE (mapping_tool);
CREATE INDEX v6_d2g_HUGE ON d2g_HUGE (mapping_confident);
CREATE TABLE "d2g_VAR"("entrez_id" INT,"relative_position" VARCHAR,"distance" VARCHAR,"variation_id" VARCHAR,"variation_source" VARCHAR,"chromosome_name" VARCHAR,"position" INT,"allele" VARCHAR,"study_type" VARCHAR,"study_external_ref" VARCHAR,"study_description" TEXT,"study_source" VARCHAR,"phenotype_description" TEXT,"associated_variant_risk_allele" VARCHAR,"p_value" REAL,"term_id" VARCHAR,"term_name" VARCHAR,"mapping_tool" VARCHAR,"mapping_confident" INT);
CREATE INDEX v4_d2g_VAR ON d2g_VAR (entrez_id);
CREATE INDEX v2_d2g_VAR ON d2g_VAR (term_id);
CREATE INDEX v3_d2g_VAR ON d2g_VAR (term_name);
CREATE INDEX v5_d2g_VAR ON d2g_VAR (variation_id);
CREATE INDEX v8_d2g_VAR ON d2g_VAR (relative_position);
CREATE INDEX v6_d2g_VAR ON d2g_VAR (mapping_tool);
CREATE INDEX v7_d2g_VAR ON d2g_VAR (mapping_confident);
CREATE INDEX d2g_VAR_distance ON d2g_VAR (distance);
CREATE INDEX d2g_VAR_chromosome_name ON d2g_VAR (chromosome_name);
CREATE INDEX d2g_VAR_position ON d2g_VAR (position);
CREATE TABLE "source_GENERIF" ("entrez_id" INTEGER DEFAULT (null) ,"pubmed_id" VARCHAR DEFAULT (null) ,"rif" TEXT);
CREATE INDEX v1_entrez_id ON source_GENERIF (entrez_id);
CREATE INDEX v2_pubmed_id ON source_GENERIF (pubmed_id);
CREATE INDEX source_HUGE_entrez_id ON source_HUGE (entrez_id);
CREATE INDEX v1_variation_id ON source_VAR (variation_id);
CREATE INDEX v2_variation_source ON source_VAR (variation_source);
CREATE INDEX v3_chromosome_name ON source_VAR (chromosome_name);
CREATE INDEX v4_position ON source_VAR (position);
CREATE INDEX v5_position ON source_VAR (entrez_id);
CREATE INDEX v6_position ON source_VAR (relative_position);
CREATE INDEX v7_position ON source_VAR (distance);
CREATE TABLE "d2g_GENERIF" ("entrez_id" INT,"pubmed_id" VARCHAR DEFAULT (null) ,"rif" TEXT,"term_id" VARCHAR,"term_name" VARCHAR,"mapping_tool" VARCHAR,"mapping_confident" INT);
CREATE INDEX v2_d2g_GENERIF ON d2g_GENERIF (term_id);
CREATE INDEX v3_d2g_GENERIF ON d2g_GENERIF (term_name);
CREATE INDEX v4_d2g_GENERIF ON d2g_GENERIF (entrez_id);
CREATE INDEX v5_d2g_GENERIF ON d2g_GENERIF (pubmed_id);
CREATE INDEX v7_d2g_GENERIF ON d2g_GENERIF (mapping_tool);
CREATE INDEX v6_d2g_GENERIF ON d2g_GENERIF (mapping_confident);
CREATE TABLE "homologene" ("group_id" INTEGER,"tax_id" INTEGER ,"entrez_id" INTEGER ,"gene_symbol" VARCHAR);
CREATE INDEX homologene_group_id ON homologene (group_id);
CREATE INDEX homologene_tax_id ON homologene (tax_id);
CREATE INDEX homologene_entrez_id ON homologene (entrez_id);
CREATE INDEX homologene_gene_symbol ON homologene (gene_symbol);
COMMIT;
